/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';


import {
  Anchor,
} from './components/custom-details/custom-details';


declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface CustomContainer {

    }

    interface CustomDetails {
      'getDefaultKnobEPosition': () => Anchor;
      'sayHelloWorldOnConsole': () => void;
    }
  }


    interface HTMLCustomContainerElement extends StencilComponents.CustomContainer, HTMLStencilElement {}

    var HTMLCustomContainerElement: {
      prototype: HTMLCustomContainerElement;
      new (): HTMLCustomContainerElement;
    };
    

    interface HTMLCustomDetailsElement extends StencilComponents.CustomDetails, HTMLStencilElement {}

    var HTMLCustomDetailsElement: {
      prototype: HTMLCustomDetailsElement;
      new (): HTMLCustomDetailsElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'custom-container': JSXElements.CustomContainerAttributes;
    'custom-details': JSXElements.CustomDetailsAttributes;
    }
  }

  namespace JSXElements {

    export interface CustomContainerAttributes extends HTMLAttributes {

    }

    export interface CustomDetailsAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'custom-container': HTMLCustomContainerElement
    'custom-details': HTMLCustomDetailsElement
  }

  interface ElementTagNameMap {
    'custom-container': HTMLCustomContainerElement;
    'custom-details': HTMLCustomDetailsElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;